name: Sync Fork from Upstream

on:
  schedule:
    - cron: '*/5 * * * *'  # Chạy mỗi 5 phút
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Fork
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Đảm bảo lấy toàn bộ lịch sử commit

      - name: Setup Git
        run: |
          git config --global user.name "Vinh Hung"
          git config --global user.email "hungphaolo02@gmail.com"

      - name: Add Upstream Remote
        run: git remote add upstream https://github.com/annguyn2303/testgithub.git

      - name: Fetch Upstream Changes
        run: git fetch upstream

      - name: Merge Upstream Changes
        run: git merge upstream/main

      - name: Pull Remote Changes
        run: git pull origin main

      - name: Push to Fork
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin main
